name: introduction-to-python

channels:
  - defaults

dependencies:
  - pip
  - python=3.12
  - pip:
    - jupyterlab
    - numpy
    - matplotlib
    - pendulum
    - okpy
    - pybryt>=0.7.0
    - pytest